### ISSUE TITLE
solicitud y recomendación

### ISSUE THREAD

**Issue by eldelassombras** [AlejoBros/Administrador-Clinica-Veterinaria#1]
Estimado, te felicito por tu trabajo, una parte de el se ajusta a unas necesidades que tengo, seria posible subas la estructura de la db en algun archivo <code>.sql</code>, adicionalmente te recomendaría borrar el archivo de configuración (y cambiar las credenciales en dicho servidor) <code>ftp.php</code>, si lo revisas me comprenderás en seguida.

saludos y ojala puedas subir la db.

**Comment by alejobrosxd2** [comment]
hola, gracias por la recomendacion y puedes encontrar el archivo acv.sql
